[package]
name = "multi-party-ecdsa"
version = "0.1.0"
authors = [
    "Gary <gary@kzencorp.com>",
    "Morten Dahl <mortendahlcs@gmail.com>",
    "Omer <omer.shlomovits@gmail.com>"
]
keywords = [
    "ecdsa",
    "multi-party-ecdsa",
    "signature",
    "rust",
    "secret-shares",
    "blockchain",
    "cryptography",
    "cryptocurrency"]

homepage = "https://github.com/KZen-networks/multi-party-ecdsa"
repository = "https://github.com/KZen-networks/multi-party-ecdsa"
license = "GPL-3.0-or-later"
categories = ["cryptography"]

[lib]
crate-type = ["lib"]

[dependencies]
cryptography-utils = { git = "https://github.com/KZen-networks/cryptography-utils" , branch = "rewrite_ec_abstract", features =  ["curvesecp256k1"]}
paillier = { git = "https://github.com/mortendahl/rust-paillier", branch = "dev" }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

[dev-dependencies]
bencher = "0.1"

[[bench]]
name = "keygen"
path = "benches/two_party_ecdsa/lindell_2017/keygen.rs"
harness = false